mysite/bookshop/urls.py
from django.urls import path
from . import views

app_name="bookshop"
urlpatterns = [
    
    path('', views.questions, name="question"), # Launch to all question
    
    path('<int:quiz_id>/', views.each_quiz, name="each_quiz"), # each question with answers and option to vote
    
    path('<int:quiz_id>/vote', views.vote, name="vote"), # Vote action
    
    path('<int:quiz_id>/results', views.results, name="results"),  # Results after voting
    
    
    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('bookshop.urls') ),
    path('admin/', admin.site.urls),
 
]

mysite/bookshop/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here.

class Question(models.Model):
    question_txt=models.CharField("Question Text", max_length=200)
    pub_date=models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_txt
    
    
    def recently_added(self):
        return self.pub_date >=timezone.now() - datetime.timedelta(days=1)
        

class Answers(models.Model):
    question= models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_txt=models.CharField(max_length=150)
    votes= models.IntegerField(default=0)
    
    def __str__(self):
        return self.answer_txt
    

mysite/bookshop/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Answers
from django.template import loader


# to use render from django.shortcuts
from django.shortcuts import render

# Return the 404 Error if the Questions are present
from django.shortcuts import get_object_or_404

from django.urls import reverse

#import the F fxn
from django.db.models import F

# Create your views here.

def hello(request):
    return HttpResponse('Welcome to Django. The road has just begun')


# using loader to fetch the template via get_template() method

def questions(request):
    # list the questions from the latest date (5)
    latest_quiz_list=Question.objects.order_by('-pub_date')[:5]
    
    # #cast to template
    # template= loader.get_template('bookshop/index.html')
    
    # context={
    #     "latest_quiz_list": latest_quiz_list,
    # }
    # # # loop through to return a string
    # # response= '\t'.join([q.question_txt for q in latest_quiz_list])
    
    # return HttpResponse(template.render(context, request))
    return render(request, "bookshop/index.html", {
        "latest_quiz_list": latest_quiz_list,
    })


# display each question and the associated answer
def each_quiz(request, quiz_id):
    # if not found, return HTTP 404 Error.
    the_quiz=get_object_or_404(Question, pk=quiz_id)
    #detail_template=loader.get_template('bookshop/detail.html')
    
    content={
        'each_quiz': the_quiz
    }
  
        
    return render(request, 'bookshop/each_quiz.html', content)


# Voting action fxnality
def vote(request, quiz_id):
    # print(quiz_id)
    question = get_object_or_404(Question, pk=quiz_id)
    try:
        selected_answer = question.answers_set.get(pk=request.POST["ans"])
    except (KeyError, Answers.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "bookshop/each_quiz.html",
            {
                "each_quiz": question,
                "error_message": "You didn't select an answer.",
            },
        )
    else:
        # using the F() to prevent the race condition incase of multiple voting coincidentally
        selected_answer.votes =F("votes")+1
        selected_answer.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        
        # using the HttpResponseRedirect() which takes 1 positional arguement "url" to the redirecting page optionall args can be given too as below.
        return HttpResponseRedirect(reverse("bookshop:results", args=(question.id,)))
    
    
    
def results(request, quiz_id):
    question = get_object_or_404(Question, pk=quiz_id)
    return render(request, "bookshop/results.html", {"question": question})

mysite/bookshop/templates/bookshop/detail.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>This is the page to view the clicked Question</h1> <br/>
        
      <h2>  {{ each_quiz.question_txt }} </h2>
        <!--list the possible answers-->
        {% for ans in each_quiz.answers_set.all %}
        <li> {{ans.answer_txt}}</li>
        {% endfor %}
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>

mysite/bookshop/templates/bookshop/each_quiz.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>This is the page to view each Question and its answers</h1> <br/>
        
        {% comment %} <!--Display the question-->
   <h2>  {{ each_quiz.question_txt }} </h2>

        <!--list the possible answers-->
        {% for ans in each_quiz.answers_set.all %}
        <li> {{ans.answer_txt}}</li>
        {% endfor %}
         {% endcomment %}
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->


        <!--Form implementation-->
        <form action="{% url 'bookshop:vote' each_quiz.id%}" method="post">
            {% csrf_token %} <!--Security-->
            <fieldset>

                <legend><h1>{{ each_quiz.question_txt }}</h1></legend>

                {% if error_message %}<p style="color:red;"><strong>{{ error_message }}</strong></p>{% endif %}
                {% for ans in each_quiz.answers_set.all %}
                    <input type="radio" name="ans" id="ans{{ forloop.counter }}" value="{{ ans.id }}">
                    <label for="ans{ forloop.counter }}">{{ ans.answer_txt }}</label><br>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Vote">
            </form> 
        
        <script src="" async defer></script>
    </body>
</html>

mysite/bookshop/templates/bookshop/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->

<html>
    <head>
        <meta charset="utf-8">

        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title> Landing page </title>


        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>

        <!--[if lt IE 7]>

            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        
        
            <![endif]-->

        
        <script src="" async defer></script>
These are all the questions present under Index.html

 
        {% if latest_quiz_list %}
    <ul>
    {% for question in latest_quiz_list %}
    <!-- The hardcodded url-->
       <!-- <li><a href="/each_quiz/{{ question.id }}/">{{ question.question_txt }}</a></li>

       -->
       <!--A better and Dynamic URL with url name-->
       <li><a href="{% url 'bookshop:each_quiz' question.id %}">{{ question.question_txt }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
    </body>
</html>

mysite/bookshop/templates/bookshop/results.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>results</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>

        {% comment %} Results implementation {% endcomment %}

        <h1>{{ question.question_txt }}</h1>

        <ul>
        {% for ans in question.answers_set.all %}
            <li>{{ ans.answer_txt }} 	&#10132; {{ ans.votes }} votes</li>
        {% endfor %}
        </ul>

        
        <!--Redirect to the exact question page to revote-->
        <a href="{% url 'bookshop:each_quiz' question.id %}">Vote again?</a>
        
        <script src="" async defer></script>
    </body>
</html>